// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIa_r7DFBfqWwYdAmbP8nOpi2nucU9VYY',
    appId: '1:1042699936190:android:8c12fb89fd058261ae99ef',
    messagingSenderId: '1042699936190',
    projectId: 'refresher-pbma',
    storageBucket: 'refresher-pbma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg2VniNNRj3upPfkydJbNw6poBhR5RelM',
    appId: '1:1042699936190:ios:510f04005aaadef0ae99ef',
    messagingSenderId: '1042699936190',
    projectId: 'refresher-pbma',
    storageBucket: 'refresher-pbma.firebasestorage.app',
    androidClientId: '1042699936190-1eqjnc3sech97c8jvk0cq8feq3vqv3at.apps.googleusercontent.com',
    iosClientId: '1042699936190-6crtn098eq1ta7pl1v417fgeobs1etvl.apps.googleusercontent.com',
    iosBundleId: 'com.app.refreshpbma.sk',
  );

}